services:  
  subconverter:
    # image: tindy2013/subconverter:latest
    image: ghcr.io/metacubex/subconverter:latest
    container_name: subconverter
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./custom:/base/custom
      - ./profiles:/base/profiles
      - ./pref.toml:/base/pref.toml
      # - ./gistconf.ini:/base/gistconf.ini
      # - ./insert-nodes.yml:/base/custom/insert-nodes.yml
    ports:
      - 25500:25500
    restart: unless-stopped

